# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import os
import pathlib
import typing
__all__ = [
    "QiDataFIle",
    "QiHeader",
]

@typing.final
class QiDataFIle:
    r"""
    Main Class for reading Qi data files.
    """
    @property
    def location(self) -> pathlib.Path: ...
    @property
    def header(self) -> typing.Any: ...
    def __new__(cls, location: builtins.str | os.PathLike | pathlib.Path) -> QiDataFIle:
        r"""
        Creating a new QiDataFile, requires the location to where the file is stored.
        """
    def get_channel_data(self, name: builtins.str, segment: builtins.int) -> numpy.typing.NDArray[numpy.float64]: ...
    def get_channels(self) -> builtins.list[builtins.str]: ...

@typing.final
class QiHeader:
    ...

